import type { DataDoc, FieldSchema, GeneratorBackend, JsonValue } from './types';

const DOT_DOCS_URL = 'https://fabricmc.net/develop/templates/datagen/';

function snakeToUpper(name: string): string {
  return name.replace(/(-)|\./g, '_').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function toItemConstant(itemId: string): string {
  const value = typeof itemId === 'string' ? itemId : 'minecraft:air';
  const parts = value.split(':');
  const path = parts[parts.length - 1] ?? 'air';
  return `Items.${snakeToUpper(path)}`;
}

function toRecipeName(recipeId: string): string {
  const value = typeof recipeId === 'string' && recipeId ? recipeId : 'item';
  const parts = value.split(':');
  return parts[parts.length - 1] ?? 'item';
}

function asArray(value: JsonValue | undefined): JsonValue[] {
  return Array.isArray(value) ? value : [];
}

function genShapeless(doc: DataDoc): string {
  const data = doc.data;
  const ingredients = asArray(data.ingredients)
    .map((entry) => (entry && typeof entry === 'object' ? toItemConstant(String((entry as Record<string, JsonValue>).item ?? '')) : toItemConstant(String(entry))))
    .filter(Boolean);
  if (ingredients.length === 0) ingredients.push('Items.AIR');
  const criterion = ingredients[0] ?? 'Items.AIR';
  const result = toItemConstant(String(data.result ?? 'minecraft:air'));
  const count = typeof data.count === 'number' ? data.count : 1;
  return [
    `@Override`,
    `public void generateRecipeData(RecipeExporter writer) throws IOException {`,
    `    // Shapeless recipe generated by DataLoom (placeholder backend)`,
    ``,
    `    ShapelessRecipeJsonBuilder.create(${result}, ${count})`,
    `            .input(${criterion})`,
    `            .criterion("has_item", RecipeProvider.conditionsFromItem(${criterion}))`,
    `            .offerTo(writer, "${toRecipeName(String(data.recipeId ?? ''))}");`,
    `}`,
  ].join('\n');
}

function genShaped(doc: DataDoc): string {
  const data = doc.data;
  const pattern = asArray(data.pattern).map(String);
  const keys = (data.key && typeof data.key === 'object' ? (data.key as Record<string, JsonValue>) : {});
  const keyLines = Object.entries(keys).map(
    ([k, v]) => `            .input(Character.valueOf('${k}'), ${toItemConstant(String(v))})`,
  );
  if (pattern.length === 0) pattern.push('aaa');
  const criterion = toItemConstant(String(keys['a'] ?? 'minecraft:air'));
  const result = toItemConstant(String(data.result ?? 'minecraft:air'));
  const count = typeof data.count === 'number' ? data.count : 1;
  return [
    `@Override`,
    `public void generateRecipeData(RecipeExporter writer) throws IOException {`,
    `    // Shaped recipe generated by DataLoom (placeholder backend)`,
    ``,
    `    ShapedRecipeJsonBuilder.create(${result}, ${count})`,
    `            .pattern(${pattern.map((p) => `"${p}"`).join(', ')})`,
    ...keyLines,
    `            .criterion("has_item", RecipeProvider.conditionsFromItem(${criterion}))`,
    `            .offerTo(writer, "${toRecipeName(String(data.recipeId ?? ''))}");`,
    `}`,
  ].join('\n');
}

function genSmelting(doc: DataDoc): string {
  const data = doc.data;
  const ingredient = toItemConstant(String(data.ingredient ?? 'minecraft:air'));
  const result = toItemConstant(String(data.result ?? 'minecraft:air'));
  const experience = typeof data.experience === 'number' ? data.experience : 0.1;
  const cookingTime = typeof data.cookingTime === 'number' ? data.cookingTime : 200;
  return [
    `@Override`,
    `public void generateRecipeData(RecipeExporter writer) throws IOException {`,
    `    // Furnace recipe generated by DataLoom (placeholder backend)`,
    ``,
    `    CookingRecipeJsonBuilder.create(Ingredient.ofItems(${ingredient}), RecipeCategory.FOOD, ${result}, ${(experience).toFixed(2)}f, ${cookingTime})`,
    `            .criterion("has_item", RecipeProvider.conditionsFromItem(${ingredient}))`,
    `            .offerTo(writer, "${toRecipeName(String(data.recipeId ?? ''))}");`,
    `}`,
  ].join('\n');
}

const recipeSchema: FieldSchema[] = [
  {
    key: 'recipeId',
    label: 'Recipe ID',
    type: 'string',
    help: 'Identifier used for the generated recipe file name.',
    placeholder: 'bone_from_iron_ingot',
  },
  { key: 'recipeType', label: 'Recipe Type', type: 'select', options: [
    { value: 'shapeless', label: 'Shapeless (craft_shapeless)' },
    { value: 'shaped', label: 'Shaped (craft_shaped)' },
    { value: 'smelting', label: 'Smelting (smelting)' },
  ] },
  { key: 'ingredients', label: 'Ingredients', type: 'array', itemType: 'object', itemFields: [
    { key: 'item', label: 'Item', type: 'string', placeholder: 'minecraft:iron_ingot' },
  ] },
  { key: 'pattern', label: 'Pattern', type: 'array', itemType: 'string', help: 'One string per row (shaped recipes only).' },
  { key: 'result', label: 'Result', type: 'string', placeholder: 'minecraft:iron_block' },
  { key: 'count', label: 'Count', type: 'number' },
  { key: 'ingredient', label: 'Ingredient (smelting)', type: 'string', placeholder: 'minecraft:raw_iron' },
  { key: 'experience', label: 'Experience (smelting)', type: 'number' },
  { key: 'cookingTime', label: 'Cooking time (smelting)', type: 'number' },
];

const recipeBackend: GeneratorBackend = {
  id: 'placeholder-recipe',
  label: 'Recipe',
  docType: 'recipe',
  defaultDoc: {
    type: 'recipe',
    data: {
      recipeId: 'iron_block_from_iron_ingot',
      recipeType: 'shapeless',
      ingredients: [
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
        { item: 'minecraft:iron_ingot' },
      ],
      result: 'minecraft:iron_block',
      count: 1,
    },
  },
  schema: recipeSchema,
  generateJava(doc: DataDoc): string {
    const recipeType = String(doc.data.recipeType ?? 'shapeless');
    const body =
      recipeType === 'shaped' ? genShaped(doc) :
      recipeType === 'smelting' ? genSmelting(doc) :
      genShapeless(doc);
    return [
      `package com.example.datagen;`,
      ``,
      `import net.minecraft.data.recipes.CookingRecipeJsonBuilder;`,
      `import net.minecraft.data.recipes.RecipeCategory;`,
      `import net.minecraft.data.recipes.RecipeExporter;`,
      `import net.minecraft.data.recipes.ShapedRecipeJsonBuilder;`,
      `import net.minecraft.data.recipes.ShapelessRecipeJsonBuilder;`,
      `import net.minecraft.tags.ItemTags;`,
      `import net.minecraft.world.item.Items;`,
      `import net.minecraft.world.item.crafting.Ingredient;`,
      `import net.minecraft.world.item.Item;`,
      `import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;`,
      `import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;`,
      ``,
      `public class MyRecipeProvider extends FabricRecipeProvider {`,
      `    public MyRecipeProvider(FabricDataOutput output) {`,
      `        super(output);`,
      `    }`,
      ``,
      body,
      `}`,
      ``,
    ].join('\n');
  },
};

export const REGISTRY: GeneratorBackend[] = [recipeBackend];

export function getBackend(id: string | null): GeneratorBackend {
  return REGISTRY.find((backend) => backend.id === id) ?? recipeBackend;
}

export { DOT_DOCS_URL };
